name: Deploy Frontend

on:
  push:
    branches: [ main ]   # change if your branch is master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist   # for VITE build (or ./build for CRA)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
