name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]   # change if your branch is master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3   # <--- USE v3 (latest)

        with:
          path: ./dist   # use ./build for CRA

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3   # <--- USE v3 (latest)
